#!/usr/bin/env python3
"""Sync auto-bmad's extra review layers into ``_bmad/custom/bmad-build-auto.toml``.

auto-bmad's review extras ride INSIDE ``bmad-build-auto``'s review step, not in the orchestrator:
BMAD resolves a skill's customization as ``<skill>/customize.toml`` -> ``_bmad/custom/<skill>.toml``
(team) -> ``_bmad/custom/<skill>.user.toml`` (personal), tables deep-merged and
``[[workflow.review_layers]]`` merged **by ``id``** (a repeated id silently REPLACES the earlier
table, then new ids are appended). This script owns ONE marker-fenced **managed region** at the END
of the team file, ``_bmad/custom/bmad-build-auto.toml``::

    # >>> auto-bmad managed review layers — generated by auto-bmad v0.26.1; do not edit between the markers (re-run /auto-bmad reprovision)
    ...                       (rendered from assets/bmad-custom/bmad-build-auto.toml)
    # <<< auto-bmad managed review layers

and renders into it the layers the runtime config enables:

  * ``auto-bmad-security``      iff ``code_review.security_layer: true`` (absent key => true). Its
    instruction launches a context-free security-reviewer subagent; the model preference baked into
    the first sentence comes from the profile ``phase_profiles.security_layer`` names
    (``claude.model``, ``codex.model``, ``codex.reasoning_effort``). A blank/missing mapping, a
    profile that does not exist, or a profile without those blocks degrades that sentence to
    "Launch a context-free subagent, synchronously, with this prompt." (per-tool clauses that ARE
    available are kept — the preference is best-effort anyway: build-auto's own step-04 rule lets
    the parent run every reviewer at the session's model capability).
  * ``auto-bmad-cross-model``   iff ``code_review.cross_model_layer`` is ``codex`` | ``claude`` |
    ``opencode`` (``""``/absent => off). Its instruction tells build-auto's parent to save the diff
    to a temp file and run ONE shell command — built by the sibling ``cli_delegate.py``
    (``resolve_layer()``: tool + model/effort from ``phase_profiles.cross_model_layer``'s profile,
    the literal ``<DIFF_FILE>`` token, the absolute project root inlined, an optional GNU
    ``timeout`` wrapper detected on PATH at bake time) — and return its stdout as the layer result.

Everything OUTSIDE the markers is preserved byte-for-byte (user tables before or after the region,
comments, whatever). The region is replaced in place when present, appended at EOF (one blank line
before) when absent, and the file is created when missing (first line
``# created by auto-bmad — team customization of bmad-build-auto (see the skill's customize.toml for the schema)``).
Both layers disabled => the region (markers included) is REMOVED; the file itself is deleted only
when it holds nothing but that creation marker and whitespace (a whitespace-only file WITHOUT the
marker is not ours — it is left in place, holding the empty remainder). The WHOLE resulting file is validated
with ``tomllib`` before anything is written (invalid => no write, exit 2). Instruction values are
TOML literal multi-line strings (``'''``): the runtime placeholder ``{diff_output}`` survives verbatim
and no ``{skill-root}``/``{project-root}`` token is ever emitted (paths are absolute); a baked value
containing ``'''`` is rejected.

Runs at setup (first-run flow), on ``/auto-bmad reprovision``, and when the Phase 0 provisioning-
freshness step (``--check``) says ``needs_apply``. Removing a layer = re-run with it disabled.

Guards (both modes):
  * **duplicate ids outside the region** — one of OUR ids in a ``[[workflow.review_layers]]`` table
    outside the markers of the same file => ERROR (exit 2, no write). BMAD merges by id, so one of
    the two definitions is silently dead: a user table BEFORE the region is replaced by ours, one
    AFTER it silently wins. Rename the user layer, or disable the auto-bmad layer and reprovision.
    (Only enabled ids are errors; a disabled layer's id outside the region is a warning.)
  * **user overrides** — our ids present in ``_bmad/custom/bmad-build-auto.user.toml`` => WARNING
    only (the personal layer legitimately replaces the team table).
  * an unbalanced / repeated marker pair, an unparseable existing file, or an unparseable config
    (missing profile, bad tool) => ERROR, no write.

Usage:
    build_auto_custom.py --project-root DIR --config FILE [--profiles-source FILE] [--asset FILE]
                         [--module-yaml FILE] --apply|--check
    build_auto_custom.py --self-test

  --project-root DIR     absolute project root; the target is DIR/_bmad/custom/bmad-build-auto.toml
  --config FILE          the runtime config ({output_folder}/auto-bmad/config.yaml)
  --profiles-source FILE fallback for the ``profiles:`` / ``phase_profiles:`` blocks when the config
                         lacks them (default: the shipped assets/profiles.yaml)
  --asset FILE           the region template (default: assets/bmad-custom/bmad-build-auto.toml)
  --module-yaml FILE     where ``module_version`` comes from (default: assets/module.yaml)

Output — ONE JSON object on stdout.
  --apply: ``{status: applied|noop, file, created_file, region_removed, file_deleted, layers: [id...],
            region_bytes, warnings, errors}``; exit 0 (applied/noop), 2 (error — nothing written).
  --check: ``{status: fresh|stale|missing|error, needs_apply, file, file_present, layers_expected,
            layers_present_in_region, duplicate_ids_outside_region, user_layer_overrides, toml_valid,
            cross_model: {enabled, tool, binary_on_path}, warnings, errors}``;
            exit 0 fresh, 1 needs_apply (stale/missing), 2 error.
  A failure raised inside resolution (bad config, unreadable asset, unwritable target) prints the
  SAME key set as that mode's success, with ``status: "error"``, ``errors: [...]`` and a convenience
  ``message`` (see ``error_result()``) — exit 2, nothing written.
  ``stale`` = the region is present but differs from what the config renders now (a retuned profile,
  a flipped layer, a module-version drift in the open marker, a region that must go); ``missing`` =
  layers are expected but the file or the region is absent.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import shutil
import sys
import tempfile
import tomllib
from pathlib import Path

REGION_OPEN_PREFIX = "# >>> auto-bmad managed review layers"
REGION_CLOSE = "# <<< auto-bmad managed review layers"
CREATION_MARKER = (
    "# created by auto-bmad — team customization of bmad-build-auto "
    "(see the skill's customize.toml for the schema)"
)
TARGET_REL = Path("_bmad") / "custom" / "bmad-build-auto.toml"
USER_TARGET_REL = Path("_bmad") / "custom" / "bmad-build-auto.user.toml"
SECURITY_ID = "auto-bmad-security"
CROSS_MODEL_ID = "auto-bmad-cross-model"
OUR_IDS = (SECURITY_ID, CROSS_MODEL_ID)
LAYER_HEADER = "[[workflow.review_layers]]"
DEGRADED_SENTENCE = "Launch a context-free subagent, synchronously, with this prompt."
_SEC_SENTENCE_RE = re.compile(
    r"^(?P<lead>Launch a context-free subagent, synchronously, with this prompt\. "
    r"If your platform lets you choose the model for that subagent, use: )"
    r"Claude Code — model `@@SEC_CLAUDE_MODEL@@`; "
    r"Codex — model `@@SEC_CODEX_MODEL@@`, reasoning effort `@@SEC_CODEX_EFFORT@@`"
    r"(?P<tail>; otherwise .*)$"
)
_FORBIDDEN_REGION_TOKENS = ("{skill-root}", "{project-root}")

_HERE = Path(__file__).resolve().parent
DEFAULT_ASSET = _HERE.parent / "assets" / "bmad-custom" / "bmad-build-auto.toml"
DEFAULT_MODULE_YAML = _HERE.parent / "assets" / "module.yaml"
DEFAULT_PROFILES_SOURCE = _HERE.parent / "assets" / "profiles.yaml"


class BuildError(Exception):
    """A resolution/rendering problem that must stop the run (exit 2, no write)."""


# --- sibling import -------------------------------------------------------------------------

def _load_cli_delegate():
    """Import the sibling ``cli_delegate.py`` (dash-free name, so a plain importlib load works)."""
    path = _HERE / "cli_delegate.py"
    spec = importlib.util.spec_from_file_location("cli_delegate", path)
    if spec is None or spec.loader is None:  # pragma: no cover - only if the sibling vanished
        raise BuildError(f"cannot import sibling script {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_cli = _load_cli_delegate()


# --- config reading -----------------------------------------------------------------------

def _read_text(path: Path) -> str:
    with open(path, encoding="utf-8", newline="") as fh:
        return fh.read()


def module_version(module_yaml: Path) -> str:
    text = _read_text(module_yaml)
    m = re.search(r"(?m)^module_version:\s*['\"]?(\d+\.\d+\.\d+)['\"]?\s*$", text)
    if not m:
        raise BuildError(f"module_version not found in {module_yaml}")
    return m.group(1)


def effective_config_text(config_text: str, profiles_source: Path | None) -> str:
    """The config text, plus the fallback ``profiles:``/``phase_profiles:`` blocks when the config
    lacks them (the parsers take the FIRST top-level block, so the config's own blocks win)."""
    lines = config_text.splitlines()
    need_profiles = _cli.find_block(lines, "profiles") is None
    need_phase = _cli.find_block(lines, "phase_profiles") is None
    if not (need_profiles or need_phase):
        return config_text
    if profiles_source is None or not profiles_source.is_file():
        return config_text
    src = _read_text(profiles_source)
    return config_text.rstrip("\n") + "\n" + src


def _parse_bool(raw: str, key: str, default: bool) -> bool:
    val = (raw or "").strip().lower()
    if val == "":
        return default
    if val in ("true", "yes", "on"):
        return True
    if val in ("false", "no", "off"):
        return False
    raise BuildError(f"{key} = {raw!r}; expected true or false")


def read_settings(config_text: str) -> dict:
    """``{security_layer: bool, cross_model_layer: str, security_profile: str}`` from the config."""
    lines = config_text.splitlines()
    cr = _cli.parse_block_scalars(lines, "code_review")
    return {
        "security_layer": _parse_bool(cr.get("security_layer", ""), "code_review.security_layer", True),
        "cross_model_layer": (cr.get("cross_model_layer", "") or "").strip(),
        "security_profile": (_cli.parse_phase_profiles(lines).get("security_layer", "") or "").strip(),
    }


def security_models(config_text: str, profile: str) -> tuple[dict, list[str]]:
    """``{claude_model, codex_model, codex_effort}`` (blank when unavailable) + warnings."""
    out = {"claude_model": "", "codex_model": "", "codex_effort": ""}
    warnings: list[str] = []
    if not profile:
        warnings.append(
            "phase_profiles.security_layer is blank/missing — the security layer carries no model "
            "preference (degraded first sentence)"
        )
        return out, warnings
    profiles = _cli.parse_profiles(config_text)
    prof = profiles.get(profile)
    if not prof:
        warnings.append(
            f"phase_profiles.security_layer names profile '{profile}' which is not in the profiles "
            "block — the security layer carries no model preference (degraded first sentence)"
        )
        return out, warnings
    claude = prof.get("claude") or {}
    codex = prof.get("codex") or {}
    out["claude_model"] = (claude.get("model") or "").strip() if isinstance(claude, dict) else ""
    out["codex_model"] = (codex.get("model") or "").strip() if isinstance(codex, dict) else ""
    out["codex_effort"] = (codex.get("reasoning_effort") or "").strip() if isinstance(codex, dict) else ""
    if not out["claude_model"] and not out["codex_model"]:
        warnings.append(
            f"profile '{profile}' has no claude.model / codex.model — the security layer carries no "
            "model preference (degraded first sentence)"
        )
    return out, warnings


# --- template -----------------------------------------------------------------------------

def _split_template(asset_text: str) -> dict:
    """Split the asset into ``header`` (open marker + comments), the per-id table texts, and the
    close marker line. Each part keeps its trailing newline."""
    lines = asset_text.splitlines(keepends=True)
    if not lines or not lines[0].startswith(REGION_OPEN_PREFIX):
        raise BuildError("asset template must start with the region open marker")
    if lines[-1].rstrip("\r\n") != REGION_CLOSE:
        raise BuildError("asset template must end with the region close marker")
    body = lines[1:-1]
    # header = everything before the first table
    idx = next((i for i, l in enumerate(body) if l.rstrip("\r\n") == LAYER_HEADER), None)
    if idx is None:
        raise BuildError("asset template has no [[workflow.review_layers]] table")
    header = "".join(body[:idx])
    tables: dict[str, str] = {}
    cur_lines: list[str] = []
    for line in body[idx:]:
        if line.rstrip("\r\n") == LAYER_HEADER and cur_lines:
            _store_table(tables, "".join(cur_lines))
            cur_lines = []
        cur_lines.append(line)
    if cur_lines:
        _store_table(tables, "".join(cur_lines))
    return {"open": lines[0], "header": header, "tables": tables, "close": lines[-1]}


def _store_table(tables: dict, text: str) -> None:
    m = re.search(r'(?m)^id\s*=\s*"([^"]+)"\s*$', text)
    if not m:
        raise BuildError("asset template table without an `id = \"...\"` line")
    tables[m.group(1)] = text


def _security_sentence(line: str, models: dict) -> str:
    """Rewrite the template's first instruction line: bake the model preference, keep only the
    per-tool clauses that are available, or degrade to the bare launch sentence."""
    m = _SEC_SENTENCE_RE.match(line.rstrip("\r\n"))
    if not m:
        raise BuildError("asset template: the security layer's first sentence no longer matches the expected shape")
    clauses: list[str] = []
    if models.get("claude_model"):
        clauses.append(f"Claude Code — model `{models['claude_model']}`")
    if models.get("codex_model"):
        c = f"Codex — model `{models['codex_model']}`"
        if models.get("codex_effort"):
            c += f", reasoning effort `{models['codex_effort']}`"
        clauses.append(c)
    if not clauses:
        return DEGRADED_SENTENCE + "\n"
    return m.group("lead") + "; ".join(clauses) + m.group("tail") + "\n"


def _check_bake_value(name: str, value: str) -> None:
    if "'''" in value:
        raise BuildError(f"{name} contains a TOML literal-string fence (''') and cannot be baked")
    if "\n" in value or "\r" in value:
        raise BuildError(f"{name} contains a line break and cannot be baked")


def render_region(
    asset_text: str, version: str, security: bool, sec_models: dict,
    cross_model: dict | None,
) -> tuple[str, list[str]]:
    """Render the managed region text (``""`` when no layer is enabled). ``cross_model`` = the
    ``resolve_layer()`` result (``None``/disabled => no cross-model table). Returns (text, layer ids)."""
    parts = _split_template(asset_text)
    layers: list[str] = []
    out = [parts["open"].replace("@@MODULE_VERSION@@", version), parts["header"]]
    if security:
        tbl = parts["tables"].get(SECURITY_ID)
        if tbl is None:
            raise BuildError(f"asset template lacks the {SECURITY_ID} table")
        for k, v in sec_models.items():
            _check_bake_value(f"security profile {k}", v)
        lines = tbl.splitlines(keepends=True)
        for i, l in enumerate(lines):
            if "@@SEC_CLAUDE_MODEL@@" in l:
                lines[i] = _security_sentence(l, sec_models)
                break
        else:
            raise BuildError("asset template: security table has no @@SEC_CLAUDE_MODEL@@ line")
        out.append("".join(lines))
        layers.append(SECURITY_ID)
    if cross_model and cross_model.get("enabled"):
        tbl = parts["tables"].get(CROSS_MODEL_ID)
        if tbl is None:
            raise BuildError(f"asset template lacks the {CROSS_MODEL_ID} table")
        tool = str(cross_model.get("tool") or "")
        cmd = str(cross_model.get("command") or "")
        _check_bake_value("cross-model tool", tool)
        _check_bake_value("cross-model command", cmd)
        if not cmd:
            raise BuildError("cross-model layer enabled but no command was resolved")
        out.append(tbl.replace("@@CROSS_MODEL_TOOL@@", tool).replace("@@CROSS_MODEL_COMMAND@@", cmd))
        layers.append(CROSS_MODEL_ID)
    if not layers:
        return "", []
    out.append(parts["close"] if parts["close"].endswith("\n") else parts["close"] + "\n")
    text = "".join(out)
    if "@@" in text:
        m = re.search(r"@@[A-Z_]+@@", text)
        raise BuildError(f"unfilled template token {m.group(0) if m else '@@'} in the rendered region")
    for tok in _FORBIDDEN_REGION_TOKENS:
        if tok in text:
            raise BuildError(f"rendered region contains the forbidden token {tok}")
    for lid in layers:
        _validate_region_layer(text, lid)
    return text, layers


def _validate_region_layer(region: str, layer_id: str) -> None:
    try:
        data = tomllib.loads(region)
    except tomllib.TOMLDecodeError as exc:
        raise BuildError(f"rendered region is not valid TOML: {exc}") from exc
    ids = [l.get("id") for l in _layers_of(data)]
    if ids.count(layer_id) != 1:
        raise BuildError(f"rendered region must define {layer_id} exactly once (found {ids.count(layer_id)})")
    for l in _layers_of(data):
        if l.get("id") == layer_id and "{diff_output}" not in str(l.get("instruction", "")):
            raise BuildError(f"rendered {layer_id} instruction lost the {{diff_output}} placeholder")


def _layers_of(data) -> list:
    wf = data.get("workflow") if isinstance(data, dict) else None
    layers = wf.get("review_layers") if isinstance(wf, dict) else None
    return [l for l in layers if isinstance(l, dict)] if isinstance(layers, list) else []


# --- target file ---------------------------------------------------------------------------

def locate_region(text: str) -> tuple[int, int] | None:
    """(start, end) character offsets of the region (open marker line .. close marker line incl.
    its newline), or None. Unbalanced or repeated markers => BuildError."""
    opens = [m.start() for m in re.finditer(r"(?m)^" + re.escape(REGION_OPEN_PREFIX), text)]
    closes = [m for m in re.finditer(r"(?m)^" + re.escape(REGION_CLOSE) + r"[ \t]*\r?\n?", text)]
    if not opens and not closes:
        return None
    if len(opens) != 1 or len(closes) != 1:
        raise BuildError(
            f"expected exactly one managed-region marker pair (found {len(opens)} open / "
            f"{len(closes)} close markers)"
        )
    start, close_m = opens[0], closes[0]
    if close_m.start() < start:
        raise BuildError("managed-region close marker appears before the open marker")
    return start, close_m.end()


def compose(existing: str | None, region: str) -> tuple[str | None, dict]:
    """Return the new file text (``None`` = delete the file) + facts. ``existing`` None = no file."""
    facts = {"created_file": False, "region_removed": False, "file_deleted": False}
    if existing is None:
        if not region:
            return None, facts
        facts["created_file"] = True
        return CREATION_MARKER + "\n\n" + region, facts
    span = locate_region(existing)
    if span is None:
        if not region:
            return existing, facts
        base = existing
        if base and not base.endswith("\n"):
            base += "\n"
        if base and not base.endswith("\n\n"):
            base += "\n"
        return base + region, facts
    before, after = existing[: span[0]], existing[span[1]:]
    if region:
        return before + region + after, facts
    facts["region_removed"] = True
    remainder = before + after
    # Delete ONLY a file that is ours end-to-end: whitespace apart from a first non-blank line that
    # is our creation marker. A whitespace-only file WITHOUT that marker was not created by us (a
    # user placeholder, a stub some other tool owns) — leave it in place and write the remainder.
    non_blank = [l for l in remainder.splitlines() if l.strip()]
    if len(non_blank) == 1 and non_blank[0].strip() == CREATION_MARKER:
        facts["file_deleted"] = True
        return None, facts
    return remainder, facts


def outside_region_text(text: str) -> str:
    span = locate_region(text)
    if span is None:
        return text
    return text[: span[0]] + text[span[1]:]


def region_layer_ids(text: str) -> list[str]:
    span = locate_region(text)
    if span is None:
        return []
    region = text[span[0]: span[1]]
    try:
        return [str(l.get("id")) for l in _layers_of(tomllib.loads(region))]
    except tomllib.TOMLDecodeError:
        return re.findall(r'(?m)^id\s*=\s*"([^"]+)"\s*$', region)


def _toml_layer_ids(text: str) -> tuple[list[str] | None, str | None]:
    """Ids of ``[[workflow.review_layers]]`` in ``text`` (None + message when unparseable)."""
    try:
        return [str(l.get("id")) for l in _layers_of(tomllib.loads(text))], None
    except tomllib.TOMLDecodeError as exc:
        return None, str(exc)


# --- the two modes -------------------------------------------------------------------------

def _resolve(args, timeout_bin) -> dict:
    """Everything both modes need: rendered region, expected layers, guards' inputs."""
    project_root = Path(args.project_root)
    if not project_root.is_absolute():
        raise BuildError(f"--project-root must be absolute (got {args.project_root!r})")
    config_path = Path(args.config)
    if not config_path.is_file():
        raise BuildError(f"config not found: {config_path}")
    asset = Path(args.asset) if args.asset else DEFAULT_ASSET
    if not asset.is_file():
        raise BuildError(f"asset template not found: {asset}")
    myaml = Path(args.module_yaml) if args.module_yaml else DEFAULT_MODULE_YAML
    psrc = Path(args.profiles_source) if args.profiles_source else DEFAULT_PROFILES_SOURCE

    version = module_version(myaml)
    cfg = effective_config_text(_read_text(config_path), psrc)
    settings = read_settings(cfg)
    warnings: list[str] = []
    sec_models: dict = {"claude_model": "", "codex_model": "", "codex_effort": ""}
    if settings["security_layer"]:
        sec_models, w = security_models(cfg, settings["security_profile"])
        warnings.extend(w)
    cross = _cli.resolve_layer(cfg, str(project_root), timeout_bin=timeout_bin)
    if not cross.get("ok"):
        raise BuildError("cross-model layer: " + "; ".join(cross.get("errors") or ["unresolvable"]))
    region, layers = render_region(_read_text(asset), version, settings["security_layer"], sec_models, cross)
    target = project_root / TARGET_REL
    user_target = project_root / USER_TARGET_REL
    existing = _read_text(target) if target.is_file() else None
    return {
        "region": region, "layers": layers, "warnings": warnings, "target": target,
        "user_target": user_target, "existing": existing, "settings": settings, "cross": cross,
    }


def _guards(res: dict) -> tuple[list[str], list[str], list[str], list[str], bool | None]:
    """duplicate ids outside region (errors), user overrides, extra warnings, errors, toml_valid."""
    dup: list[str] = []
    overrides: list[str] = []
    warnings: list[str] = []
    errors: list[str] = []
    toml_valid: bool | None = None
    existing = res["existing"]
    if existing is not None:
        _, err = _toml_layer_ids(existing)
        toml_valid = err is None
        if err is not None:
            errors.append(f"{res['target']} is not valid TOML: {err}")
        else:
            try:
                outside_ids, oerr = _toml_layer_ids(outside_region_text(existing))
            except BuildError as exc:
                outside_ids, oerr = None, str(exc)
            if oerr is not None:
                errors.append(f"{res['target']}: {oerr}")
            else:
                for lid in OUR_IDS:
                    if lid in (outside_ids or []):
                        if lid in res["layers"]:
                            dup.append(lid)
                        else:
                            warnings.append(
                                f"{res['target']} defines review layer id {lid} outside the auto-bmad "
                                "managed region; that id is reserved for auto-bmad's (currently disabled) "
                                "layer — rename it to avoid a silent replacement when the layer is enabled"
                            )
    for lid in dup:
        errors.append(
            f"{res['target']} defines review layer id {lid} outside the auto-bmad managed region — the "
            "later table silently replaces the earlier one (BMAD merges review layers by id); rename your "
            "layer, or disable the auto-bmad layer (code_review.security_layer / cross_model_layer) and run "
            "/auto-bmad reprovision"
        )
    ut = res["user_target"]
    if ut.is_file():
        uids, uerr = _toml_layer_ids(_read_text(ut))
        if uerr is not None:
            warnings.append(f"{ut} is not valid TOML: {uerr}")
        else:
            overrides = [lid for lid in OUR_IDS if lid in (uids or []) and lid in res["layers"]]
            for lid in overrides:
                warnings.append(
                    f"{ut} overrides review layer {lid} (a personal layer replaces the team table — "
                    "auto-bmad's version will not run for you)"
                )
    return dup, overrides, warnings, errors, toml_valid


def run_apply(args, timeout_bin=None) -> tuple[dict, int]:
    res = _resolve(args, timeout_bin)
    dup, _overrides, gw, gerr, _tv = _guards(res)
    warnings = res["warnings"] + gw
    out = {
        "status": "error", "file": str(res["target"]), "created_file": False, "region_removed": False,
        "file_deleted": False, "layers": res["layers"], "region_bytes": len(res["region"].encode("utf-8")),
        "warnings": warnings, "errors": gerr,
    }
    if gerr:
        return out, 2
    new_text, facts = compose(res["existing"], res["region"])
    out.update(facts)
    if new_text is not None:
        try:
            data = tomllib.loads(new_text)
        except tomllib.TOMLDecodeError as exc:
            out["errors"].append(f"resulting file would not be valid TOML — nothing written: {exc}")
            return out, 2
        ids = [str(l.get("id")) for l in _layers_of(data)]
        for lid in res["layers"]:
            if ids.count(lid) != 1:
                out["errors"].append(f"resulting file would define {lid} {ids.count(lid)} times — nothing written")
                return out, 2
    if new_text == res["existing"]:
        out["status"] = "noop"
        return out, 0
    if new_text is None:
        if res["existing"] is not None:
            res["target"].unlink()
        out["status"] = "applied"
        return out, 0
    target = res["target"]
    if target.is_dir():
        out["errors"].append(f"{target} is a directory, not a file — nothing written")
        return out, 2
    tmp = target.with_name(target.name + ".tmp")
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(tmp, "w", encoding="utf-8", newline="") as fh:
            fh.write(new_text)
        tmp.replace(target)
    except OSError as exc:
        out["errors"].append(f"could not write {target}: {exc.__class__.__name__}: {exc}")
        return out, 2
    finally:
        # A failed replace (target is a directory, a full disk, a permission flip) must never leave
        # a stray `<name>.tmp` next to the real file. A successful replace consumed it already.
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass
    out["status"] = "applied"
    return out, 0


def error_result(mode: str, message: str, project_root: str | None = None) -> dict:
    """The mode's FULL key set, defaulted, with ``status: "error"`` + ``errors: [message]``.

    A failure raised inside resolution (a bad config, an unreadable asset) must parse with the SAME
    shape as a success, so a caller can read ``errors``/``needs_apply``/``layers`` unconditionally
    instead of special-casing a three-key error object. ``message`` is kept as an extra convenience
    key. Lockstep with ``run_apply``/``run_check``'s ``out`` dicts (asserted in the self-test).
    """
    try:
        file = str(Path(project_root) / TARGET_REL) if project_root else ""
    except TypeError:  # pragma: no cover - only a non-path project_root
        file = ""
    out = {"status": "error", "file": file, "warnings": [], "errors": [message], "message": message}
    if mode == "apply":
        out.update({
            "created_file": False, "region_removed": False, "file_deleted": False,
            "layers": [], "region_bytes": 0,
        })
    else:
        out.update({
            "needs_apply": False, "file_present": False, "layers_expected": [],
            "layers_present_in_region": [], "duplicate_ids_outside_region": [],
            "user_layer_overrides": [], "toml_valid": None,
            "cross_model": {"enabled": False, "tool": None, "binary_on_path": None},
        })
    return out


def run_check(args, timeout_bin=None) -> tuple[dict, int]:
    res = _resolve(args, timeout_bin)
    dup, overrides, gw, gerr, toml_valid = _guards(res)
    cross = res["cross"]
    tool = cross.get("tool") if cross.get("enabled") else None
    out = {
        "status": "error", "needs_apply": False, "file": str(res["target"]),
        "file_present": res["existing"] is not None,
        "layers_expected": res["layers"], "layers_present_in_region": [],
        "duplicate_ids_outside_region": dup, "user_layer_overrides": overrides,
        "toml_valid": toml_valid,
        "cross_model": {
            "enabled": bool(cross.get("enabled")), "tool": tool,
            "binary_on_path": (shutil.which(tool) is not None) if tool else None,
        },
        "warnings": res["warnings"] + gw, "errors": gerr,
    }
    if gerr:
        return out, 2
    existing = res["existing"]
    if existing is not None:
        try:
            out["layers_present_in_region"] = region_layer_ids(existing)
        except BuildError as exc:
            out["errors"].append(str(exc))
            return out, 2
    try:
        span = locate_region(existing) if existing is not None else None
    except BuildError as exc:  # pragma: no cover - already caught above
        out["errors"].append(str(exc))
        return out, 2
    current_region = existing[span[0]: span[1]] if (existing is not None and span) else ""
    if current_region == res["region"]:
        out["status"] = "fresh"
    elif not current_region:
        out["status"] = "missing"
    else:
        out["status"] = "stale"
    out["needs_apply"] = out["status"] != "fresh"
    return out, (1 if out["needs_apply"] else 0)


# --- self-test -----------------------------------------------------------------------------

_CFG_FULL = """version: 1
code_review:
  followup: recommended
  security_layer: true
  cross_model_layer: codex
profiles:
  ab-deep:
    claude:
      model: opus
      effort: xhigh
    codex:
      model: gpt-5.5
      reasoning_effort: xhigh
    opencode:
      model: ""
      variant: ""
  ab-alt-deep:
    claude: {model: sonnet, effort: xhigh}
    codex: {model: gpt-5.4, reasoning_effort: xhigh}
    opencode: {model: "", variant: ""}
  ab-security:
    claude:
      model: opus          # baked into the security layer
      effort: xhigh
    codex:
      model: gpt-5.5
      reasoning_effort: xhigh
    opencode:
      model: ""
      variant: ""
phase_profiles:
  build: ab-deep
  security_layer: ab-security
  cross_model_layer: ab-alt-deep
"""


def _run_self_test() -> int:
    import subprocess

    def _mk(root: Path, cfg: str, name: str = "config.yaml") -> Path:
        p = root / "out" / "auto-bmad" / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(cfg, encoding="utf-8")
        return p

    def _args(root: Path, cfg_path: Path, **kw):
        ns = argparse.Namespace(
            project_root=str(root), config=str(cfg_path), profiles_source=kw.get("profiles_source"),
            asset=kw.get("asset"), module_yaml=kw.get("module_yaml"),
        )
        return ns

    def _cfg(**over) -> str:
        text = _CFG_FULL
        for k, v in over.items():
            text = re.sub(rf"(?m)^  {k}: .*$", f"  {k}: {v}", text, count=1)
        return text

    with tempfile.TemporaryDirectory() as td:
        root = Path(td).resolve()
        target = root / TARGET_REL
        cfgp = _mk(root, _CFG_FULL)

        # 1. both layers, file created
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        assert code == 0 and res["status"] == "applied" and res["created_file"], res
        assert res["layers"] == [SECURITY_ID, CROSS_MODEL_ID], res
        text = target.read_text(encoding="utf-8")
        assert text.startswith(CREATION_MARKER + "\n\n" + REGION_OPEN_PREFIX), text[:200]
        assert text.rstrip("\n").endswith(REGION_CLOSE)
        ver = module_version(DEFAULT_MODULE_YAML)
        assert f"— generated by auto-bmad v{ver}; do not edit between the markers" in text
        data = tomllib.loads(text)
        layers = {l["id"]: l for l in _layers_of(data)}
        assert set(layers) == {SECURITY_ID, CROSS_MODEL_ID}
        sec = layers[SECURITY_ID]["instruction"]
        assert "Claude Code — model `opus`; Codex — model `gpt-5.5`, reasoning effort `xhigh`; otherwise" in sec, sec
        assert sec.startswith("Launch a context-free subagent, synchronously, with this prompt. If your platform")
        assert "{diff_output}" in sec and "You are a Security Reviewer." in sec
        cm = layers[CROSS_MODEL_ID]
        assert cm["name"] == "auto-bmad Cross-Model Reviewer (codex)"
        assert "codex exec -m gpt-5.4 -c model_reasoning_effort=xhigh" in cm["instruction"], cm["instruction"]
        assert f'cd "{root}"' in cm["instruction"] and "<DIFF_FILE>" in cm["instruction"]
        assert cm["instruction"].rstrip("\n").endswith("--- REVIEW CONTENT ---\n{diff_output}")
        assert "timeout" not in cm["instruction"].split("cd ")[1].split("codex")[0]  # timeout_bin="" => unwrapped
        region_txt = text[text.index(REGION_OPEN_PREFIX):]
        for tok in _FORBIDDEN_REGION_TOKENS:
            assert tok not in region_txt
        assert "@@" not in region_txt
        assert res["region_bytes"] == len(region_txt.encode("utf-8"))

        # 2. idempotence
        res2, code2 = run_apply(_args(root, cfgp), timeout_bin="")
        assert code2 == 0 and res2["status"] == "noop", res2
        assert target.read_text(encoding="utf-8") == text
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 0 and chk["status"] == "fresh" and not chk["needs_apply"], chk
        assert chk["layers_present_in_region"] == [SECURITY_ID, CROSS_MODEL_ID]
        assert chk["toml_valid"] is True and chk["cross_model"]["enabled"] and chk["cross_model"]["tool"] == "codex"
        assert isinstance(chk["cross_model"]["binary_on_path"], bool)

        # 3. timeout wrapper baked when a timeout binary is given
        res3, _ = run_apply(_args(root, cfgp), timeout_bin="/usr/bin/gtimeout")
        assert res3["status"] == "applied"
        assert "gtimeout -k 30 1200 codex exec" in target.read_text(encoding="utf-8")
        run_apply(_args(root, cfgp), timeout_bin="")  # back to unwrapped

        # 4. security only (cross-model disabled) — stale first, then apply
        cfg_sec = _mk(root, _cfg(cross_model_layer='""'), "sec.yaml")
        chk, ccode = run_check(_args(root, cfg_sec), timeout_bin="")
        assert ccode == 1 and chk["status"] == "stale" and chk["needs_apply"], chk
        assert chk["layers_expected"] == [SECURITY_ID] and chk["cross_model"] == {
            "enabled": False, "tool": None, "binary_on_path": None}
        res, code = run_apply(_args(root, cfg_sec), timeout_bin="")
        assert code == 0 and res["status"] == "applied" and res["layers"] == [SECURITY_ID]
        t = target.read_text(encoding="utf-8")
        ids = [l["id"] for l in _layers_of(tomllib.loads(t))]
        assert ids == [SECURITY_ID], ids
        assert t.count(REGION_OPEN_PREFIX) == 1 and t.count(REGION_CLOSE) == 1

        # 5. cross-model only (security off) — absent security_layer key defaults to true, so set false
        cfg_cm = _mk(root, _cfg(security_layer="false", cross_model_layer="claude"), "cm.yaml")
        res, code = run_apply(_args(root, cfg_cm), timeout_bin="")
        assert code == 0 and res["layers"] == [CROSS_MODEL_ID], res
        t = target.read_text(encoding="utf-8")
        cm = _layers_of(tomllib.loads(t))[0]
        assert cm["id"] == CROSS_MODEL_ID and "(claude)" in cm["name"]
        assert "claude -p " in cm["instruction"] and "--model sonnet --effort xhigh" in cm["instruction"]

        # 6. absent security_layer key => true; absent cross_model_layer => off
        cfg_min = _mk(root, "version: 1\ncode_review:\n  followup: recommended\nprofiles:"
                      + _CFG_FULL.split("profiles:", 1)[1], "min.yaml")
        res, code = run_apply(_args(root, cfg_min), timeout_bin="")
        assert code == 0 and res["layers"] == [SECURITY_ID], res

        # 7. none => region removed and (creation-marker-only file) deleted
        cfg_none = _mk(root, _cfg(security_layer="false", cross_model_layer='""'), "none.yaml")
        chk, ccode = run_check(_args(root, cfg_none), timeout_bin="")
        assert ccode == 1 and chk["status"] == "stale" and chk["layers_expected"] == [], chk
        res, code = run_apply(_args(root, cfg_none), timeout_bin="")
        assert code == 0 and res["status"] == "applied" and res["region_removed"] and res["file_deleted"], res
        assert not target.exists()
        res, code = run_apply(_args(root, cfg_none), timeout_bin="")
        assert code == 0 and res["status"] == "noop" and not target.exists(), res
        chk, ccode = run_check(_args(root, cfg_none), timeout_bin="")
        assert ccode == 0 and chk["status"] == "fresh" and chk["file_present"] is False and chk["toml_valid"] is None, chk

        # 8. check on a missing file with layers expected => missing / exit 1
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 1 and chk["status"] == "missing" and chk["needs_apply"], chk

        # 9. user content before AND after the region is preserved byte-for-byte; append at EOF
        target.parent.mkdir(parents=True, exist_ok=True)
        user_before = '# my team file\n[workflow]\non_complete = ""\n\n[[workflow.review_layers]]\nid = "my-layer"\nname = "Mine"\ninstruction = """\nLaunch a subagent: {diff_output}\n"""\n'
        target.write_text(user_before, encoding="utf-8")
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 1 and chk["status"] == "missing" and chk["file_present"], chk
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        assert code == 0 and res["status"] == "applied" and not res["created_file"], res
        t = target.read_text(encoding="utf-8")
        assert t.startswith(user_before + "\n" + REGION_OPEN_PREFIX), t[:300]
        ids = [l["id"] for l in _layers_of(tomllib.loads(t))]
        assert ids == ["my-layer", SECURITY_ID, CROSS_MODEL_ID], ids
        # user appends AFTER the region (a different id) — preserved, region replaced in place
        user_after = '\n[[workflow.review_layers]]\nid = "trailing"\nname = "T"\ninstruction = ""\n'
        target.write_text(t + user_after, encoding="utf-8")
        res, code = run_apply(_args(root, cfg_sec), timeout_bin="")
        assert code == 0 and res["status"] == "applied", res
        t2 = target.read_text(encoding="utf-8")
        assert t2.startswith(user_before + "\n" + REGION_OPEN_PREFIX) and t2.endswith(REGION_CLOSE + "\n" + user_after), t2[-300:]
        assert [l["id"] for l in _layers_of(tomllib.loads(t2))] == ["my-layer", SECURITY_ID, "trailing"]
        # 10. stale region (hand-edited / version drift) => stale, apply restores it
        drifted = t2.replace(f"generated by auto-bmad v{ver};", "generated by auto-bmad v0.0.1;")
        target.write_text(drifted, encoding="utf-8")
        chk, ccode = run_check(_args(root, cfg_sec), timeout_bin="")
        assert ccode == 1 and chk["status"] == "stale", chk
        res, code = run_apply(_args(root, cfg_sec), timeout_bin="")
        assert code == 0 and res["status"] == "applied" and target.read_text(encoding="utf-8") == t2
        # removing both layers keeps the user content (file NOT deleted)
        res, code = run_apply(_args(root, cfg_none), timeout_bin="")
        assert code == 0 and res["region_removed"] and not res["file_deleted"] and target.exists(), res
        t3 = target.read_text(encoding="utf-8")
        assert REGION_OPEN_PREFIX not in t3 and t3 == user_before + "\n" + user_after, t3
        # re-adding after a removal does not pile up blank lines
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        t4 = target.read_text(encoding="utf-8")
        assert code == 0 and t4.startswith(t3 + "\n" + REGION_OPEN_PREFIX) and ("\n\n\n" + REGION_OPEN_PREFIX) not in t4, t4

        # 11. duplicate id outside the region => error, no write (both modes)
        dup_file = user_before + '\n[[workflow.review_layers]]\nid = "auto-bmad-security"\nname = "Shadow"\ninstruction = """x {diff_output}"""\n'
        target.write_text(dup_file, encoding="utf-8")
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 2 and chk["status"] == "error" and chk["duplicate_ids_outside_region"] == [SECURITY_ID], chk
        assert "outside the auto-bmad managed region" in chk["errors"][0]
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        assert code == 2 and res["status"] == "error" and target.read_text(encoding="utf-8") == dup_file, res
        # the same id is only a warning when that layer is disabled
        chk, ccode = run_check(_args(root, cfg_cm), timeout_bin="")
        assert ccode == 1 and chk["duplicate_ids_outside_region"] == [] and any("reserved" in w for w in chk["warnings"]), chk
        # a duplicate placed AFTER the region is caught too
        target.write_text(user_before, encoding="utf-8")
        run_apply(_args(root, cfgp), timeout_bin="")
        target.write_text(target.read_text(encoding="utf-8") + '\n[[workflow.review_layers]]\nid = "auto-bmad-cross-model"\nname = "Late"\ninstruction = "y"\n', encoding="utf-8")
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 2 and chk["duplicate_ids_outside_region"] == [CROSS_MODEL_ID], chk

        # 12. user override in the .user.toml => warning only
        target.write_text(user_before, encoding="utf-8")
        run_apply(_args(root, cfgp), timeout_bin="")
        ut = root / USER_TARGET_REL
        ut.write_text('[[workflow.review_layers]]\nid = "auto-bmad-security"\nname = "Personal"\ninstruction = ""\n', encoding="utf-8")
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 0 and chk["status"] == "fresh" and chk["user_layer_overrides"] == [SECURITY_ID], chk
        assert any("overrides review layer auto-bmad-security" in w for w in chk["warnings"])
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        assert code == 0 and res["status"] == "noop" and any("overrides" in w for w in res["warnings"])
        ut.unlink()

        # 13. invalid existing TOML => error, no write
        target.write_text('this is = not [toml\n', encoding="utf-8")
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 2 and chk["toml_valid"] is False and chk["status"] == "error", chk
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        assert code == 2 and target.read_text(encoding="utf-8") == 'this is = not [toml\n'
        # unbalanced markers => error
        target.write_text(REGION_OPEN_PREFIX + " — generated by auto-bmad v0; x\n", encoding="utf-8")
        chk, ccode = run_check(_args(root, cfgp), timeout_bin="")
        assert ccode == 2 and any("marker" in e for e in chk["errors"]), chk
        target.unlink()

        # 14. blank security profile => degraded sentence (+ warning); missing profile likewise
        cfg_blank = _mk(root, _CFG_FULL.replace("  security_layer: ab-security\n", "  security_layer: \"\"\n"), "blank.yaml")
        res, code = run_apply(_args(root, cfg_blank), timeout_bin="")
        assert code == 0 and any("degraded" in w for w in res["warnings"]), res
        sec = {l["id"]: l for l in _layers_of(tomllib.loads(target.read_text(encoding="utf-8")))}[SECURITY_ID]["instruction"]
        assert sec.startswith(DEGRADED_SENTENCE + "\n\nYou are a Security Reviewer."), sec[:200]
        assert "If your platform lets you choose" not in sec
        cfg_missing = _mk(root, _CFG_FULL.replace("  security_layer: ab-security\n", "  security_layer: ab-nope\n"), "missing.yaml")
        res, code = run_apply(_args(root, cfg_missing), timeout_bin="")
        assert code == 0 and any("ab-nope" in w for w in res["warnings"]), res
        # partial: profile with a claude block only => the codex clause is dropped
        cfg_partial = _mk(root, _CFG_FULL.replace(
            "  ab-security:\n    claude:\n      model: opus          # baked into the security layer\n      effort: xhigh\n    codex:\n      model: gpt-5.5\n      reasoning_effort: xhigh\n",
            "  ab-security:\n    claude:\n      model: opus\n      effort: xhigh\n"), "partial.yaml")
        assert "  ab-security:\n    claude:\n      model: opus\n      effort: xhigh\n    opencode:" in cfg_partial.read_text(encoding="utf-8")
        res, code = run_apply(_args(root, cfg_partial), timeout_bin="")
        assert code == 0, res
        sec = {l["id"]: l for l in _layers_of(tomllib.loads(target.read_text(encoding="utf-8")))}[SECURITY_ID]["instruction"]
        assert "use: Claude Code — model `opus`; otherwise" in sec, sec[:400]

        # 15. profiles-source fallback when the config lacks profiles/phase_profiles blocks
        cfg_bare = _mk(root, "version: 1\ncode_review:\n  security_layer: true\n  cross_model_layer: opencode\n", "bare.yaml")
        res, code = run_apply(_args(root, cfg_bare), timeout_bin="")
        assert code == 0 and res["layers"] == [SECURITY_ID, CROSS_MODEL_ID], res
        t = target.read_text(encoding="utf-8")
        assert "opencode run --dir" in t and "(opencode)" in t
        # ... and an explicit --profiles-source pointing at a file with a custom security profile
        psrc = root / "prof.yaml"
        psrc.write_text("profiles:\n  sec-x:\n    claude: {model: haiku, effort: low}\n    codex: {model: gpt-x, reasoning_effort: low}\n  cm-x:\n    opencode: {model: \"\", variant: \"\"}\nphase_profiles:\n  security_layer: sec-x\n  cross_model_layer: cm-x\n", encoding="utf-8")
        res, code = run_apply(_args(root, cfg_bare, profiles_source=str(psrc)), timeout_bin="")
        assert code == 0 and "model `haiku`" in target.read_text(encoding="utf-8"), res
        # a config WITH its own blocks ignores the fallback
        res, code = run_apply(_args(root, cfgp, profiles_source=str(psrc)), timeout_bin="")
        assert code == 0 and "model `opus`" in target.read_text(encoding="utf-8")

        # 16. config errors => BuildError (exit 2 via main): bad tool, missing cross-model profile
        cfg_bad = _mk(root, _cfg(cross_model_layer="gemini"), "bad.yaml")
        try:
            run_apply(_args(root, cfg_bad), timeout_bin="")
            raise AssertionError("expected BuildError for a bad cross_model_layer tool")
        except BuildError as exc:
            assert "cross-model layer" in str(exc)
        cfg_noprof = _mk(root, _CFG_FULL.replace("  cross_model_layer: ab-alt-deep\n", ""), "noprof.yaml")
        try:
            run_apply(_args(root, cfg_noprof), timeout_bin="")
            raise AssertionError("expected BuildError for a missing cross_model_layer mapping")
        except BuildError as exc:
            assert "cross_model_layer" in str(exc)
        try:
            read_settings("code_review:\n  security_layer: maybe\n")
            raise AssertionError("expected BuildError for a non-boolean security_layer")
        except BuildError:
            pass
        try:
            _resolve(argparse.Namespace(project_root="rel/path", config=str(cfgp), profiles_source=None, asset=None, module_yaml=None), "")
            raise AssertionError("expected BuildError for a relative project root")
        except BuildError:
            pass

        # 17. ''' in a baked value is rejected
        cfg_fence = _mk(root, _CFG_FULL.replace("      model: opus          # baked into the security layer\n", "      model: \"op'''us\"\n"), "fence.yaml")
        try:
            run_apply(_args(root, cfg_fence), timeout_bin="")
            raise AssertionError("expected BuildError for a ''' in a baked value")
        except BuildError as exc:
            assert "'''" in str(exc)

        # 18. the shipped asset renders exactly the two ids and keeps {diff_output} in both
        asset_text = _read_text(DEFAULT_ASSET)
        region, layers = render_region(asset_text, "9.9.9", True,
                                       {"claude_model": "opus", "codex_model": "gpt-5.5", "codex_effort": "xhigh"},
                                       {"enabled": True, "tool": "codex", "command": 'cd "/p" && codex exec "<DIFF_FILE>"'})
        assert layers == [SECURITY_ID, CROSS_MODEL_ID] and "v9.9.9;" in region.splitlines()[0]
        parsed = _layers_of(tomllib.loads(region))
        assert all("{diff_output}" in l["instruction"] for l in parsed)
        assert region.endswith(REGION_CLOSE + "\n")
        region_none, layers_none = render_region(asset_text, "9.9.9", False, {}, {"enabled": False})
        assert region_none == "" and layers_none == []
        # template guard: a mutated first sentence is detected
        try:
            render_region(asset_text.replace("If your platform lets you choose", "If you may pick"), "1", True,
                          {"claude_model": "opus", "codex_model": "", "codex_effort": ""}, None)
            raise AssertionError("expected BuildError on a mutated template sentence")
        except BuildError:
            pass

        # 20. file-deletion rule (both layers disabled): ONLY a file that is ours end-to-end goes.
        # (a) unit: a whitespace-only remainder WITHOUT the creation marker is kept as-is.
        blob = "  \n" + REGION_OPEN_PREFIX + " v\n" + REGION_CLOSE + "\n\n"
        new, facts = compose(blob, "")
        assert new == "  \n\n" and facts["region_removed"] and not facts["file_deleted"], (new, facts)
        # (b) unit: marker first, whitespace otherwise => deleted (leading blank lines tolerated).
        for own in (CREATION_MARKER + "\n\n" + REGION_OPEN_PREFIX + " v\n" + REGION_CLOSE + "\n",
                    "\n" + CREATION_MARKER + "\n" + REGION_OPEN_PREFIX + " v\n" + REGION_CLOSE + "\n \n"):
            new, facts = compose(own, "")
            assert new is None and facts["file_deleted"] and facts["region_removed"], (own, new, facts)
        # (c) end to end: our own file is deleted; the same file minus the marker survives empty.
        if target.exists():
            target.unlink()
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        assert code == 0 and res["created_file"], res
        res, code = run_apply(_args(root, cfg_none), timeout_bin="")
        assert code == 0 and res["file_deleted"] and not target.exists(), res
        run_apply(_args(root, cfgp), timeout_bin="")
        target.write_text(target.read_text(encoding="utf-8").replace(CREATION_MARKER + "\n", "  \n", 1), encoding="utf-8")
        res, code = run_apply(_args(root, cfg_none), timeout_bin="")
        assert code == 0 and res["region_removed"] and not res["file_deleted"], res
        assert target.is_file() and target.read_text(encoding="utf-8").strip() == "", repr(target.read_text(encoding="utf-8"))
        target.unlink()

        # 21. an unwritable target => error exit 2 and NO stray `.tmp` left behind.
        tmp_path = target.with_name(target.name + ".tmp")
        target.mkdir(parents=True, exist_ok=True)          # a DIRECTORY where the file belongs
        res, code = run_apply(_args(root, cfgp), timeout_bin="")
        assert code == 2 and res["status"] == "error" and any("directory" in e for e in res["errors"]), res
        assert not tmp_path.exists(), tmp_path
        target.rmdir()
        root2 = root / "alt"                                # parent path is a FILE => mkdir raises
        root2.mkdir(parents=True, exist_ok=True)
        (root2 / "_bmad").write_text("not a dir\n", encoding="utf-8")
        res, code = run_apply(_args(root2, cfgp), timeout_bin="")
        assert code == 2 and res["status"] == "error" and any("could not write" in e for e in res["errors"]), res
        assert not (root2 / TARGET_REL).with_name(TARGET_REL.name + ".tmp").exists()

        # 22. error_result(): the mode's full key set, defaulted.
        ea = error_result("apply", "boom", str(root))
        assert ea["status"] == "error" and ea["errors"] == ["boom"] and ea["message"] == "boom"
        assert ea["file"] == str(root / TARGET_REL) and ea["layers"] == [] and ea["region_bytes"] == 0, ea
        ec = error_result("check", "boom")
        assert ec["file"] == "" and ec["needs_apply"] is False and ec["toml_valid"] is None, ec
        assert ec["cross_model"] == {"enabled": False, "tool": None, "binary_on_path": None}, ec

        # 19. CLI round trip: exit codes + JSON on stdout
        script = str(Path(__file__).resolve())
        base = [sys.executable, script, "--project-root", str(root), "--config", str(cfgp)]
        if target.exists():
            target.unlink()
        p = subprocess.run(base + ["--check"], capture_output=True, text=True)
        assert p.returncode == 1 and json.loads(p.stdout)["status"] == "missing", p.stdout + p.stderr
        p = subprocess.run(base + ["--apply"], capture_output=True, text=True)
        assert p.returncode == 0 and json.loads(p.stdout)["status"] == "applied", p.stdout + p.stderr
        p = subprocess.run(base + ["--check"], capture_output=True, text=True)
        assert p.returncode == 0 and json.loads(p.stdout)["status"] == "fresh", p.stdout + p.stderr
        # A resolution failure prints the mode's FULL key set (+ `message`), never a 3-key object.
        ok_apply = json.loads(subprocess.run(base + ["--apply"], capture_output=True, text=True).stdout)
        p = subprocess.run(base + ["--apply", "--config", str(cfg_bad)], capture_output=True, text=True)
        err_apply = json.loads(p.stdout)
        assert p.returncode == 2 and err_apply["status"] == "error" and err_apply["errors"], p.stdout + p.stderr
        assert set(err_apply) == set(ok_apply) | {"message"}, sorted(set(err_apply) ^ set(ok_apply))
        ok_check = json.loads(subprocess.run(base + ["--check"], capture_output=True, text=True).stdout)
        p = subprocess.run(base + ["--check", "--config", str(cfg_bad)], capture_output=True, text=True)
        err_check = json.loads(p.stdout)
        assert p.returncode == 2 and err_check["status"] == "error" and err_check["errors"], p.stdout + p.stderr
        assert set(err_check) == set(ok_check) | {"message"}, sorted(set(err_check) ^ set(ok_check))
        assert err_check["file"].endswith(str(TARGET_REL)) and err_check["needs_apply"] is False, err_check
        assert "Traceback" not in p.stderr, p.stderr
        p = subprocess.run([sys.executable, script, "--project-root", str(root)], capture_output=True, text=True)
        assert p.returncode == 2 and json.loads(p.stdout)["status"] == "error"
        p = subprocess.run(base + ["--apply", "--check"], capture_output=True, text=True)
        assert p.returncode == 2

    print("build_auto_custom.py self-test: OK")
    return 0


# --- CLI -----------------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0], add_help=True)
    ap.add_argument("--project-root")
    ap.add_argument("--config")
    ap.add_argument("--profiles-source")
    ap.add_argument("--asset")
    ap.add_argument("--module-yaml")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return _run_self_test()

    def _usage(msg: str) -> int:
        print(json.dumps({"status": "error", "message": msg, "errors": [msg]}, indent=2))
        return 2

    if args.apply == args.check:
        return _usage("exactly one of --apply / --check is required")
    if not args.project_root or not args.config:
        return _usage("--project-root and --config are required")
    mode = "apply" if args.apply else "check"

    def _fail(msg: str) -> int:
        print(json.dumps(error_result(mode, msg, args.project_root), indent=2))
        return 2

    try:
        result, code = run_apply(args) if args.apply else run_check(args)
    except BuildError as exc:
        return _fail(str(exc))
    except OSError as exc:
        return _fail(f"{exc.__class__.__name__}: {exc}")
    print(json.dumps(result, indent=2))
    return code


if __name__ == "__main__":
    sys.exit(main())
